name: Sync with Hugging Face Repo

on:
    push:
        branches:
            [main]
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
          
            - name: Sync with Hugging Face
              uses: nateraw/huggingface-sync-action@v0.0.4
              with:
                  github_repo_id: yas1nsyed/mulltrenner9000
                  huggingface_repo_id: Yas1n/mulltrenner9000
                  repo_type: space
                  private: false
                  space_sdk: gradio
                  hf_token: ${{ secrets.HF_TOKEN }}
